### ISSUE TITLE
Частичный расчет

### ISSUE THREAD

**Issue by RamzanAhmatovich** [DaniilSmirnov/DobroeMesto#1]
Када галочку нажимаешь отжимаешь несколько раз сумма увеличивается как будто ты добавляешь в заказ

**Comment by DaniilSmirnov** [comment]
В Работе

**Comment by DaniilSmirnov** [comment]
Исправлено

**Comment by DaniilSmirnov** [comment]
А нет, не пофиксил

**Comment by DaniilSmirnov** [comment]
Теперь точно исправлено, коммит залит
