### ISSUE TITLE
Редактирование базы

### ISSUE THREAD

**Issue by RamzanAhmatovich** [DaniilSmirnov/DobroeMesto#13]
В окно не влезают кнопки сделай сука больше хуле тебе так жалко то

**Comment by RamzanAhmatovich** [comment]
М заебись в поле название названия не влезают причем слева хз как ты так обосраться умудрился

**Comment by RamzanAhmatovich** [comment]
Ой блять тут вообще весь интерфейс по пизде даже тестить не буду у тебя там столбцы в рабониках сползли друг на друга

**Comment by DaniilSmirnov** [comment]
BY DESIGN
