### ISSUE TITLE
Частичная оплата

### ISSUE THREAD

**Issue by RamzanAhmatovich** [DaniilSmirnov/DobroeMesto#15]
Желательно чтобы то что оплатил убиралось из списка

**Comment by RamzanAhmatovich** [comment]
Ну и заказ пустой если то закрывался

**Comment by DaniilSmirnov** [comment]
> Желательно чтобы то что оплатил убиралось из списка

Так и должно быть

**Comment by DaniilSmirnov** [comment]
by design
