### ISSUE TITLE
Разобраться с тоталами и расчетом

### ISSUE THREAD

**Issue by RamzanAhmatovich** [DaniilSmirnov/DobroeMesto#4]

**Comment by RamzanAhmatovich** [comment]
При создании нового заказа его сумма нон(скорее всего ты не обновляешь тоталы при создании нового заказа и приходится минуту ждать)

**Comment by RamzanAhmatovich** [comment]
Цена товаров пишется без скидки даже когда авторизуешь клиента по карте

**Comment by RamzanAhmatovich** [comment]
> Напиши на кнопке удаления из заказа удалить, а то хуй пойми че это за облако

Дебил иконки не скачал

**Comment by DaniilSmirnov** [comment]
Ты нахуя все закрыл то

**Comment by RamzanAhmatovich** [comment]
> Цена товаров пишется без скидки даже когда авторизуешь клиента по карте

При этот тотал считается уже со скидкой,странная хуйня,с порядком расчетов значит проблема  у тебя

**Comment by RamzanAhmatovich** [comment]
> При создании нового заказа его сумма нон(скорее всего ты не обновляешь тоталы при создании нового заказа и приходится минуту ждать)

судя по тому ,что через время тотал считается,мое предположение верно

**Comment by DaniilSmirnov** [comment]
Тотал исправлю сейчас, отображение товаров со скидкой - отложено
