### ISSUE TITLE
Сделать списание позиций из заказа

### ISSUE THREAD

**Issue by RamzanAhmatovich** [DaniilSmirnov/DobroeMesto#6]
Было бы симс гачи добавить удаление из заказа и тут для совсем дебилов

**Comment by RamzanAhmatovich** [comment]
![image](https://user-images.githubusercontent.com/50752975/57955056-6f3f7700-78fd-11e9-9082-dc209661b6e6.png)
Ну ты понял

**Comment by DaniilSmirnov** [comment]
Уже пробитая позиция не удаляется, это тока через списание
