### ISSUE TITLE
Интерфейс

### ISSUE THREAD

**Issue by RamzanAhmatovich** [DaniilSmirnov/DobroeMesto#9]
Увеличь окн нового заказа(собсна просмотра тоже) шоб он где то на пол экрана жопу показывал

**Comment by RamzanAhmatovich** [comment]
![image](https://user-images.githubusercontent.com/50752975/57958647-242b6100-7909-11e9-900a-94a0d2bc5048.png)
Это родинка на члене?

**Comment by DaniilSmirnov** [comment]
Окна увеличил, залью в некст коммите

**Comment by RamzanAhmatovich** [comment]
Ну хуя пиздык как грица зуле так длинно
